### ISSUE TITLE
Team 2: If a plane has more engines is it more likely to be struck by a bird?

### ISSUE THREAD

**Issue by JoshFerge** [CSCI-4830-002-2014/hackathon-birdstrikes#12]
Possible outcome: More engines equals more bird strikes.

Possible outcome: Less engines equals more bird strikes.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8551620/4451687/faaeac24-4839-11e4-8f95-f592e84d29a4.png)

It seems there is a high inverse correlation between number of engines and number of bird strike incidents (no commercial airplanes models have just three engines).

**Comment by chrisbopp** [comment]
Should a plane with four small engines be looked at differently than one with two giant ones? Is the surface area of air intake a better measure?

**Comment by ghost** [comment]
Not necessarily. If a plane with four engines loses one, it can still fly safely. If a plane with two engines or one engine loses one, then it must make an emergency landing which greatly increases the likelihood of injuries.

**Comment by JoshFerge** [comment]
Does the number of incidents follow the same correlation between # of engines?

**Comment by ghost** [comment]
It does not. The airplanes with two plane engines have way more incidents that airplanes with one or four engines. It may be because most commercial airplanes have two engines. Apparently, there are airplanes with three engines. 

![image](https://cloud.githubusercontent.com/assets/8551620/4451942/89e5b776-483e-11e4-8381-3d17a9abac00.png)

**Comment by JoshFerge** [comment]
Could it be that the one-engine planes might be flown in states with high numbers of injuries? could you investigate that claim?

**Comment by ghost** [comment]
Sure. It looks like they flew through the more dangerous states.

![image](https://cloud.githubusercontent.com/assets/8551620/4452055/7dc4fd92-4840-11e4-87b6-d0356bff4ea6.png)
