### ISSUE TITLE
What phase of the flight did the bird strike occur?

### ISSUE THREAD

**Issue by dano8957** [CSCI-4830-002-2014/hackathon-birdstrikes#15]

**Comment by nikitavoskoboynik** [comment]
During approach, was when the most bird strikes occurred.

![screen shot 2014-09-29 at 6 30 23 pm](https://cloud.githubusercontent.com/assets/8550866/4451652/380aa2ea-4839-11e4-96f2-b77d8c093ede.png)

**Comment by doubleshow** [comment]
Is total number of records equal to the number of birds?

**Comment by nikitavoskoboynik** [comment]
No, total number of records is the number of incidents. The number of birds is different.
