### ISSUE TITLE
Team 2: How much does the average bird strike cost to repair? How much was was the maximum cost?

### ISSUE THREAD

**Issue by adrian-chen** [CSCI-4830-002-2014/hackathon-birdstrikes#2]
How much does the average bird strike cost to repair? How much was was the maximum cost?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8551620/4451664/81f4e2c6-4839-11e4-82c4-ab99a2b43585.png)

**Comment by adrian-chen** [comment]
That maximum cost is surpising based on the cost of these planes.
![screen shot 2014-09-29 at 6 40 15 pm](https://cloud.githubusercontent.com/assets/8551273/4451723/787e2012-483a-11e4-8488-2e4452a1070f.png)
