### ISSUE TITLE
Team 2: Does the speed of the plane affect how many bird strikes occur?

### ISSUE THREAD

**Issue by JoshFerge** [CSCI-4830-002-2014/hackathon-birdstrikes#21]
Possible Outcome: The higher the speed the more the strikes. Maybe planes need to slow down

Possible Outcome: There is no relation between the two, no action to be taken.

**Comment by justinmcbride** [comment]
![tabch002](https://cloud.githubusercontent.com/assets/7710325/4451692/0bca31d6-483a-11e4-8ae2-5cb525dccbca.png?raw=true)

Wildlife strikes occur at all speeds, but apparently more damage in terms of cost occurs at lower speeds.

**Comment by doubleshow** [comment]
100+ birds, which phase?

**Comment by JoshFerge** [comment]
what about number of incidents in relation to speed?

**Comment by justinmcbride** [comment]
![speedvshits](https://cloud.githubusercontent.com/assets/7710325/4452021/f8efea78-483f-11e4-9a9d-f044168d8401.png)

This is a better graph showing the speed of the plans vs the total number of records. It also shows the height above the ground in color to show that the height also correlates with the number of incidents.
