### ISSUE TITLE
Team 1; What airlines are most notorious for crashing into birds

### ISSUE THREAD

**Issue by jakewhite8** [CSCI-4830-002-2014/hackathon-birdstrikes#23]
Potentially the airlines that primarily fly through migratory paths

**Comment by nikitavoskoboynik** [comment]
The answer is military planes. If asking about commercial airlines, United Airlines is the most notorious for crashing into birds.
![screen shot 2014-09-29 at 6 27 36 pm](https://cloud.githubusercontent.com/assets/8550866/4451622/b5846b9e-4838-11e4-9032-c29d69874308.png)

**Comment by chrisbopp** [comment]
Taking into account the number of in-flight hours, what is the normalized rate? Military planes might just be in the air more.

**Comment by nikitavoskoboynik** [comment]
I thought about that as well, but there is no data on how long the flights were, so there is not way to take that into account.

**Comment by jakewhite8** [comment]
i just measured the amount of days each airline was in the air
http://i.imgur.com/WZISSBB.png
if my data is correct it looks like united airlines and southwest are both in the air each day more than the military
