### ISSUE TITLE
Team 2 : What bird caused the most damage?

### ISSUE THREAD

**Issue by peymanmortazavi** [CSCI-4830-002-2014/hackathon-birdstrikes#25]

**Comment by peymanmortazavi** [comment]
Expected : a big fat bird !

We can study the behavior of this bird, where it lives, etc. to help come up with a solution to reduce the number of future incidents.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8551620/4451586/0f96f418-4838-11e4-9ace-579c16e393ff.png)

**Comment by peymanmortazavi** [comment]
How about 'Total Cost' instead of 'Repair cost'?  total cost could include the treatment of passengers, possible damages to the roads or airport, etc.

**Comment by ghost** [comment]
The graph is almost exactly the same.

![image](https://cloud.githubusercontent.com/assets/8551620/4451982/55717786-483f-11e4-9e94-b254f5f5f3be.png)
