### ISSUE TITLE
Is there a correlation between the time of day that a bird strike happens relative to plane damage costs?

### ISSUE THREAD

**Issue by dano8957** [CSCI-4830-002-2014/hackathon-birdstrikes#27]

**Comment by peymanmortazavi** [comment]
![a](https://cloud.githubusercontent.com/assets/5572218/4451642/0b6b09be-4839-11e4-8951-ba952cb89798.png)

Right in the middle of the month, birds get really angry and cause some good damage to the planes.

**Comment by develra** [comment]
Let's now look at the total amount of flights on the 15th of each month. Use this to figure: what is the percentage my flight on the 15th will cause my death? Keep in mind this involves a different metric. We are no longer looking at flight damage on the 15th. We are looking at passenger fatalities.
