### ISSUE TITLE
Team 3: Do most strikes happen during taxiing, take-off, flight, or landing? Is this related to the number of on-land or in-air animals struck?

### ISSUE THREAD

**Issue by alne4294** [CSCI-4830-002-2014/hackathon-birdstrikes#31]

**Comment by adrian-chen** [comment]
During the Approach phase the most birds are hit.
![screen shot 2014-09-29 at 6 30 13 pm](https://cloud.githubusercontent.com/assets/8551273/4451639/fd307b18-4838-11e4-8a71-6bde1021c9ea.png)
