### ISSUE TITLE
What is the most common type of bird sent to the Smithsonian? [Team 1] 

### ISSUE THREAD

**Issue by develra** [CSCI-4830-002-2014/hackathon-birdstrikes#4]
Possible Outcomes: A type of bird! I really am not sure more specifically. 

Possible Steps:
1. Load Data into Tablau/Splunk
2. Count and sort data
3. Possibly throw out non-bird values.

**Comment by rodenr** [comment]
![image](http://i.imgur.com/DYFJGKh.png)

**Comment by develra** [comment]
![image](https://www.dropbox.com/s/71yywxlouh9pswy/Screenshot%202014-09-29%2019.25.39%282%29.png?dl=1)
