### ISSUE TITLE
Team 2: What States Do Strikes Most Often Happen in?

### ISSUE THREAD

**Issue by JoshFerge** [CSCI-4830-002-2014/hackathon-birdstrikes#6]
Possible outcome: There is no clear state where more bird strikes happen than others. not any action to be taken.

Possible outcome: A certain states or few certain states have more bird strikes than the rest of the states. Maybe airplanes should stay out of those states.

**Comment by jakewhite8** [comment]
http://i.imgur.com/QxDu5kb.png

NC and PA change their path for no one

[team 1]
