### ISSUE TITLE
Team 2 : What was the most vulnerable aircraft?

### ISSUE THREAD

**Issue by peymanmortazavi** [CSCI-4830-002-2014/hackathon-birdstrikes#9]
We can study the most vulnerable aircraft to learn the reasons that causes vulnerability then we can work on them and try to improve the aircraft to reduce the chances of future incidents.

I'd imagine a small aircraft built for reasons other than carrying people.

**Comment by alne4294** [comment]
Team 3:

The B-737-300 has the most number of strikes.  However, we would need to know the ratio of the number of strikes to the total number of flights to infer if it's actually more vulnerable than other aircrafts.

![screen shot 2014-09-29 at 6 49 46 pm](https://cloud.githubusercontent.com/assets/2325930/4451799/ce764fca-483b-11e4-8bf2-1b304ee048d7.png)
